select stName as 'State Name'
from HOUSING_UNITS_STATE_LEVEL, POP_ESTIMATE_NATION_STATE_PR
where (HOUSING_UNITS_STATE_LEVEL.state = POP_ESTIMATE_NATION_STATE_PR.state ) and cast(POP_ESTIMATE_NATION_STATE_PR.estimatesbase2010 as float)/cast(HOUSING_UNITS_STATE_LEVEL.huestbase2010 as float) >
(select (cast (sum(POP_ESTIMATE_NATION_STATE_PR.estimatesbase2010) as float)/cast(sum(HOUSING_UNITS_STATE_LEVEL.huestbase2010)as float))
from POP_ESTIMATE_NATION_STATE_PR,HOUSING_UNITS_STATE_LEVEL
WHERE HOUSING_UNITS_STATE_LEVEL.state = POP_ESTIMATE_NATION_STATE_PR.state)
GROUP BY stNAME;
