select stname as 'State Name'
from HOUSING_UNITS_STATE_LEVEL, POP_ESTIMATE_NATION_STATE_PR
where (POP_ESTIMATE_NATION_STATE_PR.deaths2010 > POP_ESTIMATE_NATION_STATE_PR.births2010) and (POP_ESTIMATE_NATION_STATE_PR.state = HOUSING_UNITS_STATE_LEVEL.state);
