SELECT RACE.RACE_DESC as 'Race_Desc', SEX_DESC as 'Sex_Desc',SUM(CENSUS2010POP) as 'Population'
FROM POP_ESTIMATE_STATE_AGE_SEX_RACE_ORIGIN, RACE, SEX
WHERE POP_ESTIMATE_STATE_AGE_SEX_RACE_ORIGIN.RACE = RACE_CD AND POP_ESTIMATE_STATE_AGE_SEX_RACE_ORIGIN.SEX = SEX_CD AND SEX.SEX_CD != 0 AND POP_ESTIMATE_STATE_AGE_SEX_RACE_ORIGIN.ORIGIN != 0
GROUP BY RACE_CD, SEX_CD
ORDER BY SUM(CENSUS2010POP) DESC;



SELECT TOP 10 *  
FROM Company
ORDER BY Capital DESC

SELECT C.cName, P.Salary
FROM Company C INNER JOIN People P
WHERE C.PrimaryCEO = P.PrimaryCEO
ORDER BY P.Salary DESC 
LIMIT 10

